import { ArrowLeft, Banknote, Clock3, CreditCard, FileCheck2, Inbox } from "lucide-react";
import { format } from "date-fns";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useMonthContext } from "@/contexts/MonthContext";
import { useBillPaymentTransactions } from "@/hooks/useBillPaymentTransactions";

export const BillPaymentHistorySheet = ({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) => {
  const { selectedMonth, selectedYear } = useMonthContext();
  const { transactions, isLoading } = useBillPaymentTransactions(selectedMonth, selectedYear);
  const paid = transactions.filter((item) => item.status === "Paid" || item.status === "Partially Paid").reduce((sum, item) => sum + Number(item.amount), 0);
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right" className="flex w-full max-w-full flex-col bg-[#f8f9fd] p-0 dark:bg-background [&>button]:hidden sm:max-w-xl"><SheetHeader className="border-b bg-white px-3 py-2 dark:bg-card sm:px-4"><div className="flex min-h-[58px] items-center gap-2"><button type="button" onClick={() => onOpenChange(false)} className="flex h-11 w-11 items-center justify-center rounded-full hover:bg-muted" aria-label="Back"><ArrowLeft className="h-5 w-5" /></button><div className="flex-1 text-left"><SheetTitle className="text-lg font-black">Payment history</SheetTitle><p className="text-xs font-semibold text-muted-foreground">{transactions.length} records · ₹{paid.toLocaleString("en-IN")} paid</p></div></div></SheetHeader><div className="flex-1 space-y-2 overflow-y-auto px-3 py-4 sm:px-4">{isLoading ? <p className="py-10 text-center text-sm text-muted-foreground">Loading history…</p> : transactions.length === 0 ? <div className="flex flex-col items-center py-16 text-center"><Inbox className="h-10 w-10 text-muted-foreground/40" /><p className="mt-3 text-sm font-black">No recorded payments</p><p className="text-xs text-muted-foreground">Confirmed payments and attempts appear here.</p></div> : transactions.map((item) => { const Icon = item.payment_method === "Cash" ? Banknote : item.payment_method === "UPI" ? CreditCard : FileCheck2; return <article key={item.id} className="rounded-[20px] border bg-white p-4 shadow-sm dark:bg-card"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#f1efff] text-[#4936ef]"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="truncate text-sm font-black">{item.label}</p><p className="text-xs text-muted-foreground">{item.category_name} · {item.payment_method}</p></div><p className="shrink-0 text-base font-black">₹{Number(item.amount).toLocaleString("en-IN")}</p></div><div className="mt-3 flex items-center justify-between border-t pt-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${item.status === "Paid" ? "bg-emerald-100 text-emerald-700" : item.status === "Failed" ? "bg-rose-100 text-rose-700" : "bg-amber-100 text-amber-800"}`}>{item.status}</span><span className="flex items-center gap-1 text-[10px] text-muted-foreground"><Clock3 className="h-3 w-3" />{format(new Date(item.paid_at), "dd MMM, h:mm a")}</span></div>{item.note && <p className="mt-2 text-xs text-muted-foreground">{item.note}</p>}</div></div></article>; })}</div></SheetContent></Sheet>;
};
