-- ============================================================================
-- Tenant Onboarding System - New Tables (Isolated Module)
-- Does NOT modify existing tables, relationships, or migrations.
-- All onboarding data lives in dedicated tables with FK references to tenants.
-- ============================================================================

-- Enable crypto extension for gen_random_uuid() if not already enabled
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==========================================================================
-- 1. tenant_onboarding_profiles
--    Stores the full onboarding profile data for a tenant.
--    One row per tenant. Created when onboarding is initiated.
-- ==========================================================================
CREATE TABLE IF NOT EXISTS tenant_onboarding_profiles (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  pg_id           UUID NOT NULL REFERENCES pgs(id) ON DELETE CASCADE,
  owner_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Onboarding status
  status          TEXT NOT NULL DEFAULT 'not_started'
                  CHECK (status IN ('not_started','link_sent','link_viewed','form_started','form_submitted','profile_completed','pending_verification','verified','rejected')),

  -- Verification status (separate from onboarding flow status)
  verification_status TEXT NOT NULL DEFAULT 'pending'
                  CHECK (verification_status IN ('pending','verified','rejected','re_upload_requested')),

  -- Personal Information
  full_name           TEXT,
  date_of_birth       DATE,
  gender              TEXT,
  blood_group         TEXT,
  emergency_contact_name  TEXT,
  emergency_contact_phone TEXT,

  -- Identity Verification
  id_proof_type       TEXT,
  id_proof_number     TEXT,
  id_proof_url        TEXT,
  address_proof_url   TEXT,

  -- Contact Details
  email               TEXT,
  alternate_phone     TEXT,
  permanent_address   TEXT,

  -- Occupation
  occupation          TEXT,
  company_name         TEXT,
  office_address       TEXT,

  -- Stay Details
  stay_purpose        TEXT,
  expected_stay_duration TEXT,
  move_in_date        DATE,

  -- Payment Details
  payment_mode        TEXT,
  upi_id              TEXT,
  bank_account_number TEXT,
  ifsc_code           TEXT,
  bank_name           TEXT,

  -- Food Preferences
  food_preference     TEXT,
  dietary_restrictions TEXT,

  -- PG Rules & Agreement
  rules_acknowledged  BOOLEAN DEFAULT FALSE,
  agreement_accepted  BOOLEAN DEFAULT FALSE,
  agreement_signed_at TIMESTAMPTZ,

  -- Auto-save support
  form_progress       INTEGER DEFAULT 0,  -- 0-100 percentage
  last_saved_step     TEXT,

  -- Metadata
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at    TIMESTAMPTZ,
  verified_at     TIMESTAMPTZ,
  verified_by     UUID REFERENCES auth.users(id),

  UNIQUE(tenant_id)
);

-- Index for quick lookup by tenant
CREATE INDEX IF NOT EXISTS idx_onboarding_profiles_tenant_id ON tenant_onboarding_profiles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_profiles_pg_id ON tenant_onboarding_profiles(pg_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_profiles_status ON tenant_onboarding_profiles(status);

-- ==========================================================================
-- 2. tenant_onboarding_links
--    Secure onboarding links generated by the owner.
--    Contains a unique token for public access.
-- ==========================================================================
CREATE TABLE IF NOT EXISTS tenant_onboarding_links (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  pg_id           UUID NOT NULL REFERENCES pgs(id) ON DELETE CASCADE,
  owner_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token           TEXT NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(32), 'hex'),

  -- Link status tracking
  status          TEXT NOT NULL DEFAULT 'sent'
                  CHECK (status IN ('sent','viewed','started','submitted','completed','expired','revoked')),

  -- Communication tracking
  sent_via        TEXT,
  sent_at         TIMESTAMPTZ,
  viewed_at       TIMESTAMPTZ,
  started_at      TIMESTAMPTZ,
  submitted_at    TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,

  -- Expiry (default 7 days)
  expires_at      TIMESTAMPTZ DEFAULT (now() + interval '7 days'),

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_onboarding_links_token ON tenant_onboarding_links(token);
CREATE INDEX IF NOT EXISTS idx_onboarding_links_tenant_id ON tenant_onboarding_links(tenant_id);

-- ==========================================================================
-- 3. tenant_onboarding_documents
--    Documents uploaded by the tenant during onboarding.
-- ==========================================================================
CREATE TABLE IF NOT EXISTS tenant_onboarding_documents (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  onboarding_profile_id UUID NOT NULL REFERENCES tenant_onboarding_profiles(id) ON DELETE CASCADE,
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  document_type   TEXT NOT NULL,
  document_name   TEXT,
  file_url        TEXT NOT NULL,
  file_size       BIGINT,
  mime_type       TEXT,

  -- Verification status per document
  status          TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected','re_upload_requested')),
  rejection_reason TEXT,

  uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at     TIMESTAMPTZ,
  reviewed_by     UUID REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS idx_onboarding_documents_profile_id ON tenant_onboarding_documents(onboarding_profile_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_documents_tenant_id ON tenant_onboarding_documents(tenant_id);

-- ==========================================================================
-- 4. tenant_onboarding_timeline
--    Complete activity timeline for the onboarding process.
-- ==========================================================================
CREATE TABLE IF NOT EXISTS tenant_onboarding_timeline (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  pg_id           UUID NOT NULL REFERENCES pgs(id) ON DELETE CASCADE,
  onboarding_profile_id UUID REFERENCES tenant_onboarding_profiles(id) ON DELETE SET NULL,

  event_type      TEXT NOT NULL,
  event_description TEXT,
  event_metadata  JSONB DEFAULT '{}'::jsonb,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_onboarding_timeline_tenant_id ON tenant_onboarding_timeline(tenant_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_timeline_pg_id ON tenant_onboarding_timeline(pg_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_timeline_created_at ON tenant_onboarding_timeline(created_at DESC);

-- ==========================================================================
-- 5. tenant_onboarding_notifications
--    Notifications for the owner during the onboarding process.
-- ==========================================================================
CREATE TABLE IF NOT EXISTS tenant_onboarding_notifications (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id        UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  pg_id           UUID NOT NULL REFERENCES pgs(id) ON DELETE CASCADE,

  notification_type TEXT NOT NULL,
  title           TEXT NOT NULL,
  message         TEXT,
  is_read         BOOLEAN NOT NULL DEFAULT FALSE,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at         TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_onboarding_notifications_owner_id ON tenant_onboarding_notifications(owner_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_notifications_is_read ON tenant_onboarding_notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_onboarding_notifications_created_at ON tenant_onboarding_notifications(created_at DESC);

-- ==========================================================================
-- Trigger: auto-update updated_at on all onboarding tables
-- ==========================================================================

CREATE OR REPLACE FUNCTION update_onboarding_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_onboarding_profiles_updated_at
  BEFORE UPDATE ON tenant_onboarding_profiles
  FOR EACH ROW EXECUTE FUNCTION update_onboarding_updated_at();

CREATE TRIGGER trg_onboarding_links_updated_at
  BEFORE UPDATE ON tenant_onboarding_links
  FOR EACH ROW EXECUTE FUNCTION update_onboarding_updated_at();

-- ==========================================================================
-- RPC: generate_onboarding_link
--    Creates (or refreshes) an onboarding link for a tenant.
--    Returns the token + full link data.
-- ==========================================================================
CREATE OR REPLACE FUNCTION generate_onboarding_link(
  p_tenant_id UUID,
  p_pg_id UUID,
  p_owner_id UUID,
  p_sent_via TEXT DEFAULT 'whatsapp'
)
RETURNS TABLE (
  id UUID,
  token TEXT,
  status TEXT,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_existing_link RECORD;
  v_new_id UUID;
  v_new_token TEXT;
  v_expires TIMESTAMPTZ;
BEGIN
  -- Check if there's an active (non-expired, non-revoked) link
  SELECT * INTO v_existing_link
  FROM tenant_onboarding_links
  WHERE tenant_id = p_tenant_id
    AND status NOT IN ('expired', 'revoked')
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_existing_link IS NOT NULL AND v_existing_link.expires_at > now() THEN
    -- Update existing link
    UPDATE tenant_onboarding_links
    SET status = 'sent', sent_via = p_sent_via, sent_at = now()
    WHERE id = v_existing_link.id
    RETURNING id, token, status, expires_at, created_at INTO v_new_id, v_new_token, v_expires;
  ELSE
    -- Create new link
    v_expires := now() + interval '7 days';
    INSERT INTO tenant_onboarding_links (tenant_id, pg_id, owner_id, status, sent_via, sent_at, expires_at)
    VALUES (p_tenant_id, p_pg_id, p_owner_id, 'sent', p_sent_via, now(), v_expires)
    RETURNING id, token, status, expires_at, created_at INTO v_new_id, v_new_token, v_expires;
  END IF;

  -- Ensure an onboarding profile exists
  INSERT INTO tenant_onboarding_profiles (tenant_id, pg_id, owner_id, status)
  VALUES (p_tenant_id, p_pg_id, p_owner_id, 'link_sent')
  ON CONFLICT (tenant_id) DO UPDATE
    SET status = CASE
      WHEN tenant_onboarding_profiles.status = 'not_started' THEN 'link_sent'
      ELSE tenant_onboarding_profiles.status
    END,
    updated_at = now();

  -- Add timeline event
  INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
  VALUES (p_tenant_id, p_pg_id, 'link_shared', 'Onboarding link shared via ' || p_sent_via);

  RETURN QUERY SELECT v_new_id, v_new_token, 'sent', v_expires, now();
END;
$$;

-- ==========================================================================
-- RPC: validate_onboarding_link
--    Validates a token and returns tenant + onboarding data.
--    Also marks the link as viewed if it's the first access.
-- ==========================================================================
CREATE OR REPLACE FUNCTION validate_onboarding_link(p_token TEXT)
RETURNS TABLE (
  link_id UUID,
  tenant_id UUID,
  pg_id UUID,
  link_status TEXT,
  is_expired BOOLEAN,
  onboarding_status TEXT,
  verification_status TEXT,
  form_progress INTEGER,
  tenant_name TEXT,
  tenant_phone TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_link RECORD;
  v_profile RECORD;
  v_tenant RECORD;
BEGIN
  SELECT * INTO v_link
  FROM tenant_onboarding_links
  WHERE token = p_token AND status NOT IN ('revoked');

  IF v_link IS NOT FOUND THEN
    RETURN;
  END IF;

  IF v_link.expires_at < now() AND v_link.status NOT IN ('completed') THEN
    UPDATE tenant_onboarding_links SET status = 'expired' WHERE id = v_link.id;
    RETURN QUERY SELECT v_link.id, v_link.tenant_id, v_link.pg_id, 'expired', TRUE, NULL::TEXT, NULL::TEXT, NULL::INTEGER, NULL::TEXT, NULL::TEXT;
    RETURN;
  END IF;

  -- Mark as viewed if first access
  IF v_link.status = 'sent' THEN
    UPDATE tenant_onboarding_links SET status = 'viewed', viewed_at = now() WHERE id = v_link.id;

    -- Update onboarding profile status
    UPDATE tenant_onboarding_profiles
    SET status = 'link_viewed'
    WHERE tenant_id = v_link.tenant_id AND status = 'link_sent';

    -- Add timeline event
    INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
    VALUES (v_link.tenant_id, v_link.pg_id, 'link_viewed', 'Tenant viewed the onboarding link');

    -- Create notification for owner
    INSERT INTO tenant_onboarding_notifications (owner_id, tenant_id, pg_id, notification_type, title, message)
    VALUES (v_link.owner_id, v_link.tenant_id, v_link.pg_id, 'link_viewed', 'Onboarding Link Viewed', 'Your tenant has viewed the onboarding link.');
  END IF;

  -- Get profile data
  SELECT * INTO v_profile FROM tenant_onboarding_profiles WHERE tenant_id = v_link.tenant_id;
  -- Get tenant data
  SELECT name, phone INTO v_tenant FROM tenants WHERE id = v_link.tenant_id;

  RETURN QUERY SELECT
    v_link.id,
    v_link.tenant_id,
    v_link.pg_id,
    v_link.status,
    FALSE,
    COALESCE(v_profile.status, 'not_started'),
    COALESCE(v_profile.verification_status, 'pending'),
    COALESCE(v_profile.form_progress, 0),
    v_tenant.name,
    v_tenant.phone;
END;
$$;

-- ==========================================================================
-- RPC: save_onboarding_form_data
--    Auto-saves form data (partial updates to onboarding profile).
--    Also handles status transitions (form_started → form_submitted → profile_completed).
-- ==========================================================================
CREATE OR REPLACE FUNCTION save_onboarding_form_data(
  p_token TEXT,
  p_form_data JSONB,
  p_step TEXT DEFAULT NULL,
  p_progress INTEGER DEFAULT NULL,
  p_submit BOOLEAN DEFAULT FALSE
)
RETURNS TABLE (
  success BOOLEAN,
  status TEXT,
  verification_status TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_link RECORD;
  v_profile RECORD;
  v_new_status TEXT;
  v_field TEXT;
  v_value JSONB;
BEGIN
  SELECT * INTO v_link
  FROM tenant_onboarding_links
  WHERE token = p_token AND status NOT IN ('revoked', 'expired');

  IF v_link IS NOT FOUND THEN
    RETURN QUERY SELECT FALSE, NULL::TEXT, NULL::TEXT;
    RETURN;
  END IF;

  -- Get or create profile
  SELECT * INTO v_profile FROM tenant_onboarding_profiles WHERE tenant_id = v_link.tenant_id;

  IF v_profile IS NOT FOUND THEN
    INSERT INTO tenant_onboarding_profiles (tenant_id, pg_id, owner_id, status)
    VALUES (v_link.tenant_id, v_link.pg_id, v_link.owner_id, 'form_started')
    RETURNING * INTO v_profile;
  END IF;

  -- Determine new status
  IF p_submit THEN
    v_new_status := 'profile_completed';
  ELSE
    v_new_status := 'form_started';
  END IF;

  -- Update link status
  IF v_link.status = 'viewed' OR v_link.status = 'sent' THEN
    UPDATE tenant_onboarding_links SET status = 'started', started_at = now() WHERE id = v_link.id;

    -- Timeline: Form Started
    INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
    VALUES (v_link.tenant_id, v_link.pg_id, 'form_started', 'Tenant started filling the onboarding form');

    -- Notification: Form Started
    INSERT INTO tenant_onboarding_notifications (owner_id, tenant_id, pg_id, notification_type, title, message)
    VALUES (v_link.owner_id, v_link.tenant_id, v_link.pg_id, 'form_started', 'Onboarding Form Started', 'Your tenant has started filling the onboarding form.');
  END IF;

  -- Update profile with form data (field by field)
  -- We use a dynamic approach: iterate over JSON keys and update matching columns
  UPDATE tenant_onboarding_profiles SET
    full_name = COALESCE(NULLIF(p_form_data->>'full_name', ''), full_name),
    date_of_birth = CASE WHEN p_form_data ? 'date_of_birth' AND (p_form_data->>'date_of_birth') != '' THEN (p_form_data->>'date_of_birth')::DATE ELSE date_of_birth END,
    gender = COALESCE(NULLIF(p_form_data->>'gender', ''), gender),
    blood_group = COALESCE(NULLIF(p_form_data->>'blood_group', ''), blood_group),
    emergency_contact_name = COALESCE(NULLIF(p_form_data->>'emergency_contact_name', ''), emergency_contact_name),
    emergency_contact_phone = COALESCE(NULLIF(p_form_data->>'emergency_contact_phone', ''), emergency_contact_phone),
    id_proof_type = COALESCE(NULLIF(p_form_data->>'id_proof_type', ''), id_proof_type),
    id_proof_number = COALESCE(NULLIF(p_form_data->>'id_proof_number', ''), id_proof_number),
    id_proof_url = COALESCE(NULLIF(p_form_data->>'id_proof_url', ''), id_proof_url),
    address_proof_url = COALESCE(NULLIF(p_form_data->>'address_proof_url', ''), address_proof_url),
    email = COALESCE(NULLIF(p_form_data->>'email', ''), email),
    alternate_phone = COALESCE(NULLIF(p_form_data->>'alternate_phone', ''), alternate_phone),
    permanent_address = COALESCE(NULLIF(p_form_data->>'permanent_address', ''), permanent_address),
    occupation = COALESCE(NULLIF(p_form_data->>'occupation', ''), occupation),
    company_name = COALESCE(NULLIF(p_form_data->>'company_name', ''), company_name),
    office_address = COALESCE(NULLIF(p_form_data->>'office_address', ''), office_address),
    stay_purpose = COALESCE(NULLIF(p_form_data->>'stay_purpose', ''), stay_purpose),
    expected_stay_duration = COALESCE(NULLIF(p_form_data->>'expected_stay_duration', ''), expected_stay_duration),
    move_in_date = CASE WHEN p_form_data ? 'move_in_date' AND (p_form_data->>'move_in_date') != '' THEN (p_form_data->>'move_in_date')::DATE ELSE move_in_date END,
    payment_mode = COALESCE(NULLIF(p_form_data->>'payment_mode', ''), payment_mode),
    upi_id = COALESCE(NULLIF(p_form_data->>'upi_id', ''), upi_id),
    bank_account_number = COALESCE(NULLIF(p_form_data->>'bank_account_number', ''), bank_account_number),
    ifsc_code = COALESCE(NULLIF(p_form_data->>'ifsc_code', ''), ifsc_code),
    bank_name = COALESCE(NULLIF(p_form_data->>'bank_name', ''), bank_name),
    food_preference = COALESCE(NULLIF(p_form_data->>'food_preference', ''), food_preference),
    dietary_restrictions = COALESCE(NULLIF(p_form_data->>'dietary_restrictions', ''), dietary_restrictions),
    rules_acknowledged = CASE WHEN p_form_data ? 'rules_acknowledged' THEN (p_form_data->>'rules_acknowledged')::BOOLEAN ELSE rules_acknowledged END,
    agreement_accepted = CASE WHEN p_form_data ? 'agreement_accepted' THEN (p_form_data->>'agreement_accepted')::BOOLEAN ELSE agreement_accepted END,
    agreement_signed_at = CASE WHEN p_form_data ? 'agreement_accepted' AND (p_form_data->>'agreement_accepted')::BOOLEAN THEN now() ELSE agreement_signed_at END,
    form_progress = COALESCE(p_progress, form_progress),
    last_saved_step = COALESCE(p_step, last_saved_step),
    status = v_new_status,
    completed_at = CASE WHEN p_submit THEN now() ELSE completed_at END
  WHERE tenant_id = v_link.tenant_id;

  -- Update link status on submit
  IF p_submit THEN
    UPDATE tenant_onboarding_links SET status = 'completed', submitted_at = now(), completed_at = now() WHERE id = v_link.id;

    -- Timeline: Profile Completed
    INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
    VALUES (v_link.tenant_id, v_link.pg_id, 'profile_completed', 'Tenant completed and submitted the onboarding form');

    -- Timeline: Documents Uploaded (if any)
    INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
    VALUES (v_link.tenant_id, v_link.pg_id, 'documents_uploaded', 'Tenant uploaded verification documents');

    -- Notifications
    INSERT INTO tenant_onboarding_notifications (owner_id, tenant_id, pg_id, notification_type, title, message)
    VALUES
      (v_link.owner_id, v_link.tenant_id, v_link.pg_id, 'form_submitted', 'Onboarding Form Submitted', 'Your tenant has submitted the onboarding form.'),
      (v_link.owner_id, v_link.tenant_id, v_link.pg_id, 'profile_completed', 'Profile Completed', 'Tenant profile has been completed and is ready for verification.'),
      (v_link.owner_id, v_link.tenant_id, v_link.pg_id, 'verification_pending', 'Verification Pending', 'Tenant documents are pending your verification.');
  END IF;

  SELECT status, verification_status INTO v_new_status
  FROM tenant_onboarding_profiles WHERE tenant_id = v_link.tenant_id;

  RETURN QUERY SELECT TRUE, v_new_status, COALESCE((SELECT verification_status FROM tenant_onboarding_profiles WHERE tenant_id = v_link.tenant_id), 'pending');
END;
$$;

-- ==========================================================================
-- RPC: verify_tenant_onboarding
--    Owner verifies or rejects tenant onboarding.
-- ==========================================================================
CREATE OR REPLACE FUNCTION verify_tenant_onboarding(
  p_tenant_id UUID,
  p_action TEXT,
  p_rejection_reason TEXT DEFAULT NULL,
  p_verifier_id UUID
)
RETURNS TABLE (success BOOLEAN, verification_status TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_new_status TEXT;
BEGIN
  IF p_action = 'approve' THEN
    v_new_status := 'verified';
    UPDATE tenant_onboarding_profiles
    SET verification_status = 'verified', verified_at = now(), verified_by = p_verifier_id
    WHERE tenant_id = p_tenant_id;

    INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
    SELECT p_tenant_id, pg_id, 'verified', 'Tenant onboarding verified by owner'
    FROM tenant_onboarding_profiles WHERE tenant_id = p_tenant_id;

  ELSIF p_action = 'reject' THEN
    v_new_status := 'rejected';
    UPDATE tenant_onboarding_profiles
    SET verification_status = 'rejected'
    WHERE tenant_id = p_tenant_id;

    INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
    SELECT p_tenant_id, pg_id, 'rejected', 'Tenant onboarding rejected: ' || COALESCE(p_rejection_reason, 'No reason provided')
    FROM tenant_onboarding_profiles WHERE tenant_id = p_tenant_id;

  ELSIF p_action = 'request_reupload' THEN
    v_new_status := 're_upload_requested';
    UPDATE tenant_onboarding_profiles
    SET verification_status = 're_upload_requested'
    WHERE tenant_id = p_tenant_id;

    INSERT INTO tenant_onboarding_timeline (tenant_id, pg_id, event_type, event_description)
    SELECT p_tenant_id, pg_id, 're_upload_requested', 'Owner requested document re-upload: ' || COALESCE(p_rejection_reason, '')
    FROM tenant_onboarding_profiles WHERE tenant_id = p_tenant_id;
  ELSE
    RETURN QUERY SELECT FALSE, NULL::TEXT;
    RETURN;
  END IF;

  RETURN QUERY SELECT TRUE, v_new_status;
END;
$$;

-- ==========================================================================
-- Enable Row Level Security
-- ==========================================================================
ALTER TABLE tenant_onboarding_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_onboarding_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_onboarding_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_onboarding_timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_onboarding_notifications ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Owner can manage their onboarding data
CREATE POLICY "owners_manage_onboarding_profiles"
  ON tenant_onboarding_profiles FOR ALL
  USING (owner_id = auth.uid())
  WITH CHECK (owner_id = auth.uid());

CREATE POLICY "owners_manage_onboarding_links"
  ON tenant_onboarding_links FOR ALL
  USING (owner_id = auth.uid())
  WITH CHECK (owner_id = auth.uid());

CREATE POLICY "owners_manage_onboarding_documents"
  ON tenant_onboarding_documents FOR ALL
  USING (
    onboarding_profile_id IN (
      SELECT id FROM tenant_onboarding_profiles WHERE owner_id = auth.uid()
    )
  )
  WITH CHECK (
    onboarding_profile_id IN (
      SELECT id FROM tenant_onboarding_profiles WHERE owner_id = auth.uid()
    )
  );

CREATE POLICY "owners_manage_onboarding_timeline"
  ON tenant_onboarding_timeline FOR ALL
  USING (pg_id IN (SELECT id FROM pgs WHERE owner_id = auth.uid()))
  WITH CHECK (pg_id IN (SELECT id FROM pgs WHERE owner_id = auth.uid()));

CREATE POLICY "owners_manage_onboarding_notifications"
  ON tenant_onboarding_notifications FOR ALL
  USING (owner_id = auth.uid())
  WITH CHECK (owner_id = auth.uid());

-- Public read access for onboarding links (token-based, no auth required)
-- This is needed for the public tenant onboarding form
CREATE POLICY "public_read_onboarding_links_by_token"
  ON tenant_onboarding_links FOR SELECT
  USING (true);

-- Public access to save form data via RPC (SECURITY DEFINER functions handle auth)
-- The RPCs are SECURITY DEFINER so they bypass RLS
